name: r-univ-deploy

on:
  workflow_dispatch:

jobs:
  auth:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Download the thing
        run: |
            curl https://ggseg.r-universe.dev/api/snapshot/zip -Lo thing.zip
            mkdir thing
            unzip thing.zip -d thing && rm -f thing.zip

      - name: Artifactize the thing
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: thing
          path: thing
          
      - name: Extract Artifact URL
        run: |
          echo "Artifact URL is: ${{ steps.upload_artifact.outputs.artifact-url }}"
          echo "Artifact ID is: ${{ steps.upload_artifact.outputs.artifact-id }}"
          
      - name: Deploy the thing
        run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=github.pages" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          VERSION=$(date +%Y%m%d%H%M%S)
          
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pages/deployments \
              -d '{"artifact_url":"${{ steps.upload_artifact.outputs.artifact-url }}","environment":"github-pages","pages_build_version":"$VERSION","oidc_token":"$OIDC_TOKEN"}'
